name: Generate Trophy

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Trophy
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: zappybird
          theme: onedark
          margin-w: 15
          margin-h: 15

      - name: Commit trophy.svg
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add trophy.svg
          git commit -m "Update trophy" || echo "No changes"
          git push
