name: Generate Streak Stats

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
          user: zappybird
          theme: onedark
          hide_border: true
          output: profile/streak.svg

      - name: Commit streak.svg
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak" || exit 0
          git push
