name: Generate Trophy

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Trophy
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: zappybird
          theme: onedark
          margin-w: 15
          margin-h: 15
          output: profile/trophy.svg

      - name: Commit trophy.svg
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/trophy.svg
          git commit -m "Update trophy" || exit 0
          git push
